### PR TITLE
Some styling and branding fixes, as well as optimising some images.

### PR DESCRIPTION
**Pull request by FieryMewtwo**

### CODE REVIEW

**Comment by zemixe** [comment]
If you want to be accurate hekate should not be capitalized.

**Comment by FieryMewtwo** [comment]
Ok

**Comment by FieryMewtwo** [comment]
Done

**Comment by Hartie95** [comment]
I planned to overhaul the example config a bit anyway, so I will cherrypick changes, and include them together with other small changes to the example config (like adding ubuntu and using the official switchroot bootIds).
Also some small thoughts: 
Since its always rebooting anyway, I would prefer to use hekate menu (or something similar) and add the bootPos=0 to it to force the hekate menu.
I will probably also not add the `reboot to` to Lockpick RCM, since, like I mentioned, its alway rebooting anyway, so its just additional text you need to parse.
About the ums part, with it being a group, I don't think it really need hekate UMS in every entry, but renaming the group and entries a bit seems also to be a good idea.

Still thank you for your contribution, its always nice to see others interested to help improving projects. ^^

**Pull request closed without merging**
